### ISSUE TITLE
Project build failed

### ISSUE THREAD

**Issue by SoTosorrow** [oramasearch/orama#239]
**Describe the bug**
I had git clone the project like `git clone https://github.com/LyraSearch/lyra --depth=1`
then use `pnpm install`
and i get such errors
```
pass success info............

> @lyrasearch/lyra@0.4.0 build
> swc --delete-dir-on-start --extensions .ts,.cts -d dist src

failed to process input file

Caused by:
    0: failed to read swcrc file (src/index.ts)
    1: failed to canonicalize base url using the path of .swcrc
       Dir:
       (Used logic for windows)
    2: 系统找不到指定的路径。 (os error 3)  >>> means system can not find path
failed to process input file

>>> other 34 same info for different swc file

Failed to compile 35 files with swc.
Error: Failed to compile:
src/algorithms.ts
src/commonjs.cts
src/errors.ts
src/index.ts
src/insertion-checker.ts
src/internals.ts
src/levenshtein.ts
src/types.ts
src/utils.ts
src/methods/common.ts
src/methods/create.ts
src/methods/hooks.ts
src/methods/insert.ts
src/methods/load.ts
src/methods/remove.ts
src/methods/save.ts
src/methods/search.ts
src/radix-tree/node.ts
src/radix-tree/radix.ts
src/tokenizer/diacritics.ts
src/tokenizer/index.ts
src/tokenizer/languages.ts
src/tokenizer/stop-words/de.ts
src/tokenizer/stop-words/dk.ts
src/tokenizer/stop-words/en.ts
src/tokenizer/stop-words/es.ts
src/tokenizer/stop-words/fi.ts
src/tokenizer/stop-words/fr.ts
src/tokenizer/stop-words/index.ts
src/tokenizer/stop-words/it.ts
src/tokenizer/stop-words/nl.ts
src/tokenizer/stop-words/no.ts
src/tokenizer/stop-words/pt.ts
src/tokenizer/stop-words/ru.ts
src/tokenizer/stop-words/se.ts
    at initialCompilation (D:\2-code\test\lyra\node_modules\.pnpm\@swc+cli@0.1.59_@swc+core@1.3.24\node_modules\@swc\cli\lib\swc\dir.js:172:19)
    at async dir (D:\2-code\test\lyra\node_modules\.pnpm\@swc+cli@0.1.59_@swc+core@1.3.24\node_modules\@swc\cli\lib\swc\dir.js:16:5)
 ELIFECYCLE  Command failed with exit code 1.
```
I try to modify the .swcrc or re-clone, nothing useful happened.

**Desktop:**
 - OS: win10
 - npm: 8.15.0
 - node: 16.17.1
 - path: D:\2-code\test\lyra

**Comment by micheleriva** [comment]
Hi! Can you please try again? We made some major refactors, and this issue might not be present anymore

**Comment by micheleriva** [comment]
Closing due to inactivity
