### ISSUE TITLE
TypeError: Cannot destructure property 'type' of 'index.indexes[prop]' as it is undefined.

### ISSUE THREAD

**Issue by ocavue** [oramasearch/orama#486]
**Describe the bug**

I cannot use `remove` to remove a document from the database, when the schema includes a vector field.

**To Reproduce**

Create a simple script with the following content:

```js
import { create, getByID, insertMultiple, remove } from '@orama/orama'

async function main() {
  const db = await create({
    schema: {
      id: 'string',
      text: 'string',
      embedding: 'vector[384]',
    },
  })

  const doc1 = { id: 'id1', text: 'text1', embedding: Array.from({ length: 384 }).map(() => 1) }
  const doc2 = { id: 'id2', text: 'text2', embedding: Array.from({ length: 384 }).map(() => 2) }

  await insertMultiple(db, [doc1, doc2])
  console.log(await getByID(db, 'id2'))

  await remove(db, 'id2')
}

main()
```

Run this script and you will get this error:

```bash
$ node index.mjs
file:///tmp/orama-remove-issue/node_modules/.pnpm/@orama+orama@1.2.5/node_modules/@orama/orama/dist/components/index.js:202
    const { type , node  } = index.indexes[prop];
            ^

TypeError: Cannot destructure property 'type' of 'index.indexes[prop]' as it is undefined.
    at removeScalar (file:///tmp/orama-remove-issue/node_modules/.pnpm/@orama+orama@1.2.5/node_modules/@orama/orama/dist/components/index.js:202:13)
    at Object.remove (file:///tmp/orama-remove-issue/node_modules/.pnpm/@orama+orama@1.2.5/node_modules/@orama/orama/dist/components/index.js:235:16)
    at remove (file:///tmp/orama-remove-issue/node_modules/.pnpm/@orama+orama@1.2.5/node_modules/@orama/orama/dist/methods/remove.js:28:32)
    at async main (file:///tmp/orama-remove-issue/index.mjs:18:3)

Node.js v18.17.1
```

**Expected behavior**

No error 

**Screenshots**

N/A 

**Desktop (please complete the following information):**
 - macOS 
 - Node.js: 18
 - @orama/orama: 1.2.5

**Additional context**

N/A

**Comment by micheleriva** [comment]
Hi there! Fixed and released with `v1.2.6`. Thanks for spotting this
